### ISSUE TITLE
User defined TTree cann't be wrote to a second file

### ISSUE THREAD

**Issue by zoujh** [key4hep/k4FWCore#10]
When I fill a TTree and write it to a second file by myself in an algorithm:
``` c++
StatusCode AnAlgorithm::initialize()
{
    _file = TFile::Open("tmp.root", "RECREATE");
    _tree = new TTree("mytree", "testing");
    // other things .......
}

// filling _tree in execute() ......

StatusCode AnAlgorithm::finalize()
{
    // _file->cd();  // sometimes this line leads to a crash, or else the "events" TTree will be wrote to "tmp.root"
    _tree->Write();
    // other things .......
}
```

Then, `tmp.root` will be an empty file. And the `mytree` TTree is saved to the same file of EDM4hep by `PodioOutput`.

**Comment by vvolkl** [comment]
Hi @zoujh, thanks for this bug report. Probably the dataservice assumes the  `gDirectory`  is in the output file. This can be fixed, but  I think in principle, the framework should provide enough functionalities so the user shouldn't have to write a custom TFile. Any kind of branches can be written to the output file, and there is a HistogramSvc especially for saving Histograms: `https://github.com/HEP-FCC/FCCSW/blob/master/Generation/src/components/HepMCHistograms.cpp`. I also think the problem might be the same when just using Podio and  trying to use a second TFile while the EventStore is active.

**Comment by tmadlener** [comment]
Hi @vvolkl, 

>  I also think the problem might be the same when just using Podio and trying to use a second TFile while the EventStore is active.

I just wrote a few rather simple test cases for `podio` to see if that is a problem there. At least for `podio` this works as expected with `file->cd()` before writing. However, it is possible that this could break if the `TTree` gets too large to be held in memory and gets dumped partially before the call to `Write`.

**Comment by zoujh** [comment]
As an example, I add a few lines to the algorithm in k4-project-template. The code can be found at:
https://github.com/zoujh/k4-project-template
We can repeat the problem by running the option `createExampleEventData.py` in the package.
It seems that the TDirectory of all ROOT Objects is set to a single path when writing podio in FWCore.

**Comment by vvolkl** [comment]
Hi @zoujh,

this issue should finally be fixed with #23 . The problem was that the events tree is created by the dataservice, but the TFile by PodioOutput. If there is a user-created TFile, indeed the events tree can end up inside. I didn't think to check this because usually there is no need to write to a TFile in the user code (since Gaudi provides the DataSvc/PodioOutput and the HistogramSvc).
Let me know if this works for you.

**Comment by zoujh** [comment]
Hi @vvolkl,

Since I didn't find a valid Gaudi-v35 building in cvmfs, it's hard for me to test the lastest k4FWCore directly. So I made the same modification in `PodioOutput` in an older version of k4FWCore, and I can write a second `TFile` correctly then.

Thank you!

**Comment by vvolkl** [comment]
Great, I'll close this then.

Gaudi v35 is already installed on cvmfs, but not in the latest stable release (as some packages are still using v34). I already added it to the nightlies though, so you can use it with

```
source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
```

It's also possible to use spack to get a very flexible setup, I'll try to write some instructions for the CEPCSW gaudi upgrade.
