### ISSUE TITLE
Drop Legacy PODIO components

### ISSUE THREAD

**Issue by hegner** [key4hep/k4FWCore#101]
This is a reminder to drop the legacy PODIO components introduced in #100 . Their removal has in particular an impact on DataHandle and DataWrapper. 
Once the legacy components are gone, the latter should get a flag whether it owns the data or not. This would replace the currently needed 'reset' method workaround

**Comment by tmadlener** [comment]
I seem to have missed this when opening #107. Closing this in favor of that since discussion is already happening there.
