### ISSUE TITLE
Make `DataSvc` thread safe

### ISSUE THREAD

**Issue by tmadlener** [key4hep/k4FWCore#106]
As already discussed in #94 eventually we want to move to Gaudi Functional. This requires that our `DataHandle` / `DataSvc` works in a thread safe way. #100 introduces Frame based I/O but probably not yet in a thread safe enough way to make it work inside Gaudi Functional.

**Comment by tmadlener** [comment]
@jmcarcell do you want to keep this open until this is done "properly", or can we close this?

**Comment by jmcarcell** [comment]
I don't mind either. `DataHandles` are not used with `Gaudi::Functional` so the title is a bit wrong on that but it's true that the `DataSvc` is not thread-safe. And there is a third topic which is moving to `Gaudi::Functional` which is somehow independent of the other ones (but not complete if the `DataSvc` is not thread-safe)

**Comment by jmcarcell** [comment]
This is now completed by having a new service that can be used with multithreading `IOSvc`.
