### ISSUE TITLE
Legacy `GaudiAlg`, `GaudiTool`, etc. will be removed in the future

### ISSUE THREAD

**Issue by tmadlener** [key4hep/k4FWCore#114]
This has been announced at the Gaudi developers meeting on June 7, 2023. This means we should switch to the "new" family of `Gaudi::Algorithm` or ideally Gaudi Functional in order to have a smooth transition. This is also relevant for other repositories in key4hep and HEP-FCC. We can use this issue to keep an overview on related issues in the specific repositories.

**Comment by jmcarcell** [comment]
This is now complete, except for https://github.com/key4hep/k4FWCore/issues/219 since the stack is built without `GaudiAlg` now.
