### ISSUE TITLE
Alternatives for `EventCounter` removed with`GaudiAlg`

### ISSUE THREAD

**Issue by m-fila** [key4hep/k4FWCore#219]
A number of repositories uses the `EventCounter` that was part of the deprecated `GaudiAlg`:
- key4hep/k4RecTracker
- HEP-FCC/k4RecCalorimeter
- HEP-FCC/FCCDIRAC 
- HEP-FCC/fcc-tutorials
- HEP-FCC/FCCSW

The [`EventCounter`](https://gitlab.cern.ch/gaudi/Gaudi/-/blob/8dfa672f75a29371e0c02b7820989a0dc1bd689c/GaudiAlg/src/lib/EventCounter.cpp) algorithm itself is simple as it just increments its internal counter on each execution and prints the counter's value on finalize and heartbeat on execution:

- In case the heartbeat printout on execution is desired then a replacement functional algorithm using internal atomic counter could be rather easily written. It should be possible to get the same behavior as in `EventCounter`
- In case the printout only at the finalize is sufficient then there is a newer mechanism in form of `Gaudi::Accumulator::Counter` and `MessageSvcSink` (`MessageSvcSink` prints the values hold in each counter at the finalize). With it, it's possible to:
  - add `Gaudi::Accumulator::Counter` member to some algorithms that should be counted (for instance the input/output algorithms or filters) and remove the `EventCounter` from affected repositories
  - write another `EventCounter` algorithm that does just the counting (can be copied from [`GaudiTestSuite`](https://gitlab.cern.ch/gaudi/Gaudi/-/blob/8dfa672f75a29371e0c02b7820989a0dc1bd689c/GaudiTestSuite/src/FunctionalAlgorithms/EventCounter.cpp))

The solutions involving a separate algorithm doing counting would require to put it in sequential sequencer when used with the `AvalancheSchedulerSvc` (no data dependencies declared so the algorithm could be executed in any order with the respect to the other algorithms)

Alternatively, the information about the event number as seen from a scheduler can be accesses with `EventContext`

**Comment by tmadlener** [comment]
Can we have a sort of combination of things? Something like an `EventCounter` algorithm that simply prints the event number from the `EventContext` for the hearbeat with an internal `Gaudi::Accumulator::Counter` for printing the summary?

**Comment by m-fila** [comment]
> Can we have a sort of combination of things? Something like an `EventCounter` algorithm that simply prints the event number from the `EventContext` for the hearbeat with an internal `Gaudi::Accumulator::Counter` for printing the summary?

We can, no problem

As we [discussed](https://codimd.web.cern.ch/gwJuWzeORsqiMp10n_44eQ?view#Metadata-in-the-Frame) it's used  mainly for debugging and it's not clear if there are better ways to debug especially in multi-threaded environment

**Comment by giovannimarchiori** [comment]
FYI, for my own debugging I use this homemade version
https://github.com/giovannimarchiori/k4RecCalorimeter/blob/gmarchio-main-20241024-EventCounter/RecCalorimeter/src/components/EventCounter.h
https://github.com/giovannimarchiori/k4RecCalorimeter/blob/gmarchio-main-20241024-EventCounter/RecCalorimeter/src/components/EventCounter.cpp

I had seen the GaudiTestSuite EventCounter but didn't seem to do what I needed (print out event number).

It's just some temporary workaround while waiting for a better designed solution from more expert contributors than myself ;)

Cheers,
  Giovanni

**Comment by BrieucF** [comment]
Shall we include this solution here in k4FWCore or do we already have something else?

**Comment by tmadlener** [comment]
If we want to run this on multiple threads, the `m_counter` should at least be an `atomic<int>` (and potentially some atomic comparison) to avoid race conditions that might lead to bogus outputs.

**Comment by m-fila** [comment]
I couldn't find a reasonable alternative (one that isn't polluting the logs with lots of irrelevant information) so I think we can add this.

I'd like to use `Gaudi::Accumulator::Counter`for couting  so it's both atomic and generating nice summary on the outout. I'll open a PR later

**Comment by giovannimarchiori** [comment]
out of curiosity - is there a way to run k4run in multi-threaded mode?
