### ISSUE TITLE
Use podio meta data for job options 

### ISSUE THREAD

**Issue by vvolkl** [key4hep/k4FWCore#24]
The job options are written directly to the metadata tree at the moment, but they could make use of the new metadata features in podio.

**Comment by jmcarcell** [comment]
Should be solved as part of the Frame implementation. #94

**Comment by tmadlener** [comment]
Job options are stored the same way as other metadata since #100.

They are available from the `podio_metadata` frame via the `gaudiConfigOptions` key as a `std::string` parameter.
