### ISSUE TITLE
WARNING: duplicated property name

### ISSUE THREAD

**Issue by giovannimarchiori** [key4hep/k4FWCore#240]
When recompiling a nightly with k4FWCore locally downloaded, I noticed this

[ 90%] Linking CXX shared module libk4FWCorePlugins.so
WARNING duplicated property name 'Input', see https://its.cern.ch/jira/browse/GAUDI-1023
WARNING duplicated property name 'Output', see https://its.cern.ch/jira/browse/GAUDI-1023

Is that OK?

Thanks, Giovanni

**Comment by m-fila** [comment]
Yes, nothing to worry about. It's known warning and expected. From [#213](https://github.com/key4hep/k4FWCore/pull/213#issue-2417169846):
> - Use Input and Output for IOSvc, deprecate input and output since all the other properties are capitalized. The same for IOType instead of ioType. This will print a warning about a duplicated property that should be ignored for now.

**Comment by giovannimarchiori** [comment]
Thanks! Closing the issue then

**Comment by jmcarcell** [comment]
This warning will stop appearing after https://github.com/key4hep/k4FWCore/pull/297 since Gaudi checks only the lowercase name of its properties to emit it.
