### ISSUE TITLE
Discussion: Testing / CTest / Gaudi Environment

### ISSUE THREAD

**Issue by vvolkl** [key4hep/k4FWCore#33]
This concerns all framework packages (and key4hep-spack): There is an issue with testing gaudi framework components that I keep stumbling over: Due to the component/plugin mechanism, Gaudi mixes the (spack) concepts of build and run environments. In particular, while the compiler can find libraries via RPaths, ld-config ... the Gaudi plugin system needs the library to be in LD_LIBRARY_PATH to run the contained components.

When using CTest to run tests, they are run in the build environment. Gaudi provides a run script that extends the environment with the necessary variables to run the current package, but they don't cover other gaudi packages that are used in the tests.
There are several approaches to fix this: 
* All environment information could be set in CTest using the ENVIRONMENT of `add_test`
* Spack could set up the build environment of gaudi packages the same as their run environment
* The appoach I tried out here: https://github.com/HEP-FCC/k4Gen/blob/main/.github/workflows/test.yaml#L27 The package is installed first, and then ctest is run in the environment of the installed package.
* Not use ctest at all for these kind of integration test, but use a different testing mechanism. Spack can run tests on installed packages, for example: https://spack.readthedocs.io/en/latest/command_index.html#spack-test

When a view is used, all of this is of couse less of an issue.

**Comment by jmcarcell** [comment]
Closing, the environment for tests is set from the `CMakeLists.txt`.
