### ISSUE TITLE
Empty collection when saved by PodioOutput with "keep *"

### ISSUE THREAD

**Issue by SanghyunKo** [key4hep/k4FWCore#44]
When attempting to save Podio collection read by `PodioInput` using `PodioOutput` with `keep *` option, it creates an instance of Podio collection in the output file; however, the collection is empty. Hence this breaks links between PODs such as `OneToOneRelations`, throwing segfault when trying to read the output file by `podio::EventStore->get<T>(std::string)` later.

 - OS version: centos7
 - Compiler version: GCC 8.3
 - Package version: v01-00pre09
 - Reproduced by:
```bash
k4run test/k4TestFWCore/options/createExampleEventData.py # creates output_k4test_exampledata.root
k4run test/k4TestFWCore/options/readExampleEventData.py # creates output_k4test_exampledata_2.root
```

#### output_k4test_exampledata.root
![cap01](https://user-images.githubusercontent.com/37464245/119090150-35eaf600-ba46-11eb-8f22-8e0b92e6171f.png)

#### output_k4test_exampledata_2.root
![cap02](https://user-images.githubusercontent.com/37464245/119090179-3edbc780-ba46-11eb-8547-aaebfe7e2027.png)

**Comment by vvolkl** [comment]
Hi @SanghyunKo,

Interesting, that should of course be possible. Collections read from file are handled differently, I'll review that code.

**Comment by SanghyunKo** [comment]
Hi @vvolkl, thanks!

Just out of curiosity, is there any specific reason for not using `podio::ROOTWriter` for writing events? If I understand the code correctly, we are using `podio::ROOTReader` for reading but writing `podio::CollectionBase` manually.

**Comment by vvolkl** [comment]
Yes, this is mostly for historical reasons - the `podio::ROOTWriter` was only an example at first, not intended for production. There is also the question of ownership, but I don't see why the DataService couldn't own an EventStore which owns the collections. So by now we could indeed refactor this, which would also solve this issue, I think. One thing this implementation does that is not possible with the ROOTWriter at the moment is to write out stl vectors and other classes with dictionaries - I have to think what is the best solution for that.

**Comment by SanghyunKo** [comment]
I see, thanks for the explanation. Indeed the last point seems to be a clear motivation for having this implementation.
