### ISSUE TITLE
Fix getting EventStore (getProvider) in PodioDataSvc

### ISSUE THREAD

**Issue by fdplacido** [key4hep/k4FWCore#55]
When trying to get the `podio::EventStore` in `PodioDataSvc`:

https://github.com/key4hep/k4FWCore/blob/master/k4FWCore/include/k4FWCore/PodioDataSvc.h#L46

it will fail due to deleted function in podio:

https://github.com/AIDASoft/podio/blob/master/include/podio/EventStore.h#L39

Example:

```cpp
  ServiceHandle<IDataProviderSvc> m_eds ("EventDataSvc", "EDM4hep2LcioTool");
  PodioDataSvc* pds;
  pds = dynamic_cast<PodioDataSvc*>( m_eds.get());

  const podio::EventStore provider = pds->getProvider();
```

**Comment by tmadlener** [comment]
This should work if you make the `provider` a reference:
``` cpp
const podio::EventStore& provider = pds->getProvider();
```
The `EventStore` is marked as non-copyable, because there really should only be one.

**Comment by fdplacido** [comment]
Right, I don't remember what I was trying to do with the EventStore that I could not.
But that makes sense in any case so this can be closed.
