### ISSUE TITLE
IJobOptionsSvc removed in Gaudi 36.0

### ISSUE THREAD

**Issue by tmadlener** [key4hep/k4FWCore#58]
The `IJobOptionsSvc` that is used by the PodioOutput has been deprecated and removed from Gaudi v36 onwards: See [CHANGELOG](https://gitlab.cern.ch/gaudi/Gaudi/-/blob/master/CHANGELOG.md#v36r0-2021-06-21)

We are using it here:
https://github.com/key4hep/k4FWCore/blob/67e5d9452a49f4dee2c3010d0f74f925e4a11b6d/k4FWCore/components/PodioOutput.cpp#L2

It is not entirely clear to me what should be used instead.

**Comment by mirguest** [comment]
Hi Thomas,
Please see my PR #57 .
Tao

**Comment by tmadlener** [comment]
Hi Tao,
I completely missed that. Sorry. But even better if there already is a PR for that ;)
Thomas
