### ISSUE TITLE
Extend PodioDataSvc to replace GaudiHiveWhiteboard

### ISSUE THREAD

**Issue by andresailer** [key4hep/k4FWCore#64]
As stated here: https://codimd.web.cern.ch/E4TGrEhWTIOf2ac9zjvJRw#GaudiHive-in-CEPC-Driftchamber

**Comment by jmcarcell** [comment]
Same as https://github.com/key4hep/k4FWCore/issues/106, now we have `IOSvc` that can be used with `GaudiHiveWhiteboard`.
